on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
        
jobs:
  deploy:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}         
          enable-AzPSSession: true

      - name: Bicep template
        uses: azure/powershell@v1
        with:
          azPSVersion: "3.1.0"
          inlineScript: |
            $deploymentName = 'ghactionlistentogether${{ github.sha }}'
            $resourceGroupName = '${{ secrets.AZURE_RESOURCE_GROUP_NAME }}'
            $webAppName = '${{ secrets.HUB_WEBAPP_NAME }}'
            $servicePlanName = '${{ secrets.SERVICE_PLAN_NAME }}'
            $storageAccountName = '${{ secrets.STORAGE_NAME }}'
            $administratorLogin = '${{ secrets.PODCASTDB_USER_LOGIN }}'
            $administratorLoginPassword = '${{ secrets.PODCASTDB_USER_PASSWORD }}'
            $serverName = '${{ secrets.PODCASTDB_SERVER_NAME }}'
            $apiName = '${{ secrets.API_RESOURCE_NAME }}'

            az deployment group create -n "$($deploymentName)" `
               --resource-group  "$($resourceGroupName)" `
               --template-file deploy/Services/hub.bicep `
               --parameters webAppName="$($webAppName)" servicePlanName="$($servicePlanName)" storageAccountName="$($storageAccountName)" administratorLogin="$($administratorLogin)" administratorLoginPassword="$($administratorLoginPassword)" serverName="$($serverName)" apiName="$($apiName)"

      - uses: actions/download-artifact@v3
        with:
          name: drop
          path: hub

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.HUB_WEBAPP_NAME }}
          package: hub
